create schema if not exists diary;

comment on schema diary is 'Private server partition for the Diary app. Tables are not exposed to public clients by default.';

create or replace function diary.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, diary
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists diary.entries (
  id uuid primary key default gen_random_uuid(),
  entry_date date not null,
  title text not null,
  body text not null,
  body_format text not null default 'plain',
  mood text,
  source text,
  github_path text,
  github_commit_sha text,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint entries_entry_date_unique unique (entry_date),
  constraint entries_body_not_empty check (length(btrim(body)) > 0),
  constraint entries_body_format_check check (body_format in ('plain', 'markdown'))
);

create table if not exists diary.entry_assets (
  id uuid primary key default gen_random_uuid(),
  entry_id uuid not null references diary.entries(id) on delete cascade,
  storage_bucket text,
  storage_path text not null,
  mime_type text,
  alt_text text,
  sort_order integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint entry_assets_entry_path_unique unique (entry_id, storage_path)
);

create table if not exists diary.sync_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  entry_id uuid references diary.entries(id) on delete set null,
  source text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint sync_events_event_type_check check (event_type in ('import', 'create', 'update', 'delete', 'publish', 'error'))
);

create index if not exists entries_entry_date_idx on diary.entries (entry_date desc);
create index if not exists entry_assets_entry_id_sort_idx on diary.entry_assets (entry_id, sort_order, id);
create index if not exists sync_events_created_at_idx on diary.sync_events (created_at desc);
create index if not exists sync_events_entry_id_idx on diary.sync_events (entry_id);

drop trigger if exists set_entries_updated_at on diary.entries;
create trigger set_entries_updated_at
before update on diary.entries
for each row
execute function diary.set_updated_at();

alter table diary.entries enable row level security;
alter table diary.entry_assets enable row level security;
alter table diary.sync_events enable row level security;

revoke all on schema diary from anon, authenticated;
revoke all on all tables in schema diary from anon, authenticated;
revoke all on all functions in schema diary from anon, authenticated;

comment on table diary.entries is 'Canonical diary entries for the Diary app.';
comment on table diary.entry_assets is 'Optional files or images associated with diary entries.';
comment on table diary.sync_events is 'Append-only operational log for diary imports, publishing, and sync failures.';
